# Generated by Django 3.1 on 2021-11-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcell', '0001_initial'),
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company',
        ),
        migrations.AlterField(
            model_name='application',
            name='applied_to',
            field=models.ManyToManyField(blank=True, to='pcell.company'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
