# Generated by Django 3.0.7 on 2021-11-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_remove_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
    ]
