# Generated by Django 3.1 on 2021-11-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='visited_year',
            field=models.IntegerField(default=2021),
        ),
    ]
